import 'package:flutter/material.dart';
import 'package:flutterapp/merchlyapp/generatedprogresswidget/generated/GeneratedProgressachiWidget.dart';
import 'package:flutterapp/merchlyapp/generatedprogresswidget/generated/GeneratedAllachiWidget.dart';
import 'package:flutterapp/merchlyapp/generatedprogresswidget/generated/GeneratedStatisticsWidget.dart';
import 'package:flutterapp/merchlyapp/generatedprogresswidget/generated/GeneratedPointsWidget.dart';
import 'package:flutterapp/merchlyapp/generatedprogresswidget/generated/GeneratedGainedachiWidget.dart';
import 'package:flutterapp/merchlyapp/generatedprogresswidget/generated/GeneratedMenuWidget.dart';

/* Frame Progress
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProgressWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 1168.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 428.0,
                            height: 1152.0,
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 255, 255, 255),
                                    ),
                                  ),
                                  Positioned(
                                    left: 32.0,
                                    top: 25.0,
                                    right: null,
                                    bottom: null,
                                    width: 184.0,
                                    height: 17.0,
                                    child: GeneratedStatisticsWidget(),
                                  ),
                                  Positioned(
                                    left: 32.0,
                                    top: 260.0,
                                    right: null,
                                    bottom: null,
                                    width: 360.0,
                                    height: 162.0,
                                    child: GeneratedPointsWidget(),
                                  ),
                                  Positioned(
                                    left: 32.0,
                                    top: 76.0,
                                    right: null,
                                    bottom: null,
                                    width: 360.0,
                                    height: 162.0,
                                    child: GeneratedProgressachiWidget(),
                                  ),
                                  Positioned(
                                    left: 32.0,
                                    top: 444.0,
                                    right: null,
                                    bottom: null,
                                    width: 360.0,
                                    height: 300.0,
                                    child: GeneratedGainedachiWidget(),
                                  ),
                                  Positioned(
                                    left: 32.0,
                                    top: 762.0,
                                    right: null,
                                    bottom: null,
                                    width: 360.0,
                                    height: 300.0,
                                    child: GeneratedAllachiWidget(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: 0.0,
              top: 1084.0,
              right: null,
              bottom: null,
              width: 428.0,
              height: 84.0,
              child: GeneratedMenuWidget(),
            )
          ]),
    ));
  }
}
