import 'package:flutter/material.dart';
import 'package:flutterapp/merchlyapp/generatedhomewidget1/generated/GeneratedFrame2Widget.dart';
import 'package:flutterapp/merchlyapp/generatedhomewidget1/generated/GeneratedMenuWidget1.dart';
import 'package:flutterapp/merchlyapp/generatedhomewidget1/generated/GeneratedFrame1Widget.dart';

/* Frame Home
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 1141.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 428.0,
                            height: 1129.0,
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 255, 255, 255),
                                    ),
                                  ),
                                  Positioned(
                                    left: 27.0,
                                    top: 20.0,
                                    right: null,
                                    bottom: null,
                                    width: 375.0,
                                    height: 850.0,
                                    child: GeneratedFrame1Widget(),
                                  ),
                                  Positioned(
                                    left: 27.0,
                                    top: 20.0,
                                    right: null,
                                    bottom: null,
                                    width: 375.0,
                                    height: 850.0,
                                    child: GeneratedFrame2Widget(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: 1.0,
              top: 1057.0,
              right: null,
              bottom: null,
              width: 428.0,
              height: 84.0,
              child: GeneratedMenuWidget1(),
            )
          ]),
    ));
  }
}
